eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
mybatis:
  type-aliases-package: com.imooc.product.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.imooc.product.utils.MyMapper
  not-empty: false
  identity: MYSql
server:
  port: 8081
