package com.imooc.product.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "product_cate")
public class ProductCate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_cate.categoryid
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    @Id
    private Integer categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_cate.categoryname
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_cate.categorytype
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    private Integer categorytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_cate.createtime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    @JsonFormat(pattern = "yyy-MM-dd",locale = "zh")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_cate.updatetime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    @JsonFormat(pattern = "yyy-MM-dd",locale = "zh")
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_cate.categoryid
     *
     * @return the value of product_cate.categoryid
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_cate.categoryid
     *
     * @param categoryid the value for product_cate.categoryid
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_cate.categoryname
     *
     * @return the value of product_cate.categoryname
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_cate.categoryname
     *
     * @param categoryname the value for product_cate.categoryname
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_cate.categorytype
     *
     * @return the value of product_cate.categorytype
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public Integer getCategorytype() {
        return categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_cate.categorytype
     *
     * @param categorytype the value for product_cate.categorytype
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public void setCategorytype(Integer categorytype) {
        this.categorytype = categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_cate.createtime
     *
     * @return the value of product_cate.createtime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_cate.createtime
     *
     * @param createtime the value for product_cate.createtime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_cate.updatetime
     *
     * @return the value of product_cate.updatetime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_cate.updatetime
     *
     * @param updatetime the value for product_cate.updatetime
     *
     * @mbggenerated Wed Jul 25 17:30:21 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}