package com.imooc.product.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "product_info")
public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productid
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    @Id
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productname
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productprice
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private BigDecimal productprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productstock
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private Integer productstock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productdescription
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private String productdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.producticon
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private String producticon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.productstatus
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private Byte productstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.categorytype
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private Integer categorytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.createtime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.updatetime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productid
     *
     * @return the value of product_info.productid
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productid
     *
     * @param productid the value for product_info.productid
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productname
     *
     * @return the value of product_info.productname
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productname
     *
     * @param productname the value for product_info.productname
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productprice
     *
     * @return the value of product_info.productprice
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public BigDecimal getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productprice
     *
     * @param productprice the value for product_info.productprice
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductprice(BigDecimal productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productstock
     *
     * @return the value of product_info.productstock
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public Integer getProductstock() {
        return productstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productstock
     *
     * @param productstock the value for product_info.productstock
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductstock(Integer productstock) {
        this.productstock = productstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productdescription
     *
     * @return the value of product_info.productdescription
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public String getProductdescription() {
        return productdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productdescription
     *
     * @param productdescription the value for product_info.productdescription
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.producticon
     *
     * @return the value of product_info.producticon
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public String getProducticon() {
        return producticon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.producticon
     *
     * @param producticon the value for product_info.producticon
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProducticon(String producticon) {
        this.producticon = producticon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.productstatus
     *
     * @return the value of product_info.productstatus
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public Byte getProductstatus() {
        return productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.productstatus
     *
     * @param productstatus the value for product_info.productstatus
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setProductstatus(Byte productstatus) {
        this.productstatus = productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.categorytype
     *
     * @return the value of product_info.categorytype
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public Integer getCategorytype() {
        return categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.categorytype
     *
     * @param categorytype the value for product_info.categorytype
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setCategorytype(Integer categorytype) {
        this.categorytype = categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.createtime
     *
     * @return the value of product_info.createtime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.createtime
     *
     * @param createtime the value for product_info.createtime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.updatetime
     *
     * @return the value of product_info.updatetime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.updatetime
     *
     * @param updatetime the value for product_info.updatetime
     *
     * @mbggenerated Wed Jul 25 18:06:48 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}