package com.imooc.product.mapper;

import com.imooc.product.pojo.OrderMaster;
import java.util.List;

public interface OrderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbggenerated Tue Jul 31 23:28:03 CST 2018
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbggenerated Tue Jul 31 23:28:03 CST 2018
     */
    int insert(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbggenerated Tue Jul 31 23:28:03 CST 2018
     */
    OrderMaster selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbggenerated Tue Jul 31 23:28:03 CST 2018
     */
    List<OrderMaster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbggenerated Tue Jul 31 23:28:03 CST 2018
     */
    int updateByPrimaryKey(OrderMaster record);
}