package com.imooc.product.mapper;

import com.imooc.product.pojo.OrderDetail;
import java.util.List;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Tue Jul 31 00:35:23 CST 2018
     */
    int deleteByPrimaryKey(String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Tue Jul 31 00:35:23 CST 2018
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Tue Jul 31 00:35:23 CST 2018
     */
    OrderDetail selectByPrimaryKey(String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Tue Jul 31 00:35:23 CST 2018
     */
    List<OrderDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Tue Jul 31 00:35:23 CST 2018
     */
    int updateByPrimaryKey(OrderDetail record);
}